app/Http/routes.php
<?php

Route::pattern('id', '[0-9]+');
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::auth();

Route::get('/', [
    'uses'  =>  'HomeController@index',
    'as'    =>  'home'
]);

Route::get('/{id}', [
    'uses'  =>  'UsersController@show',
    'as'    =>  'user.gallery'
]);

Route::group(['prefix' => 'photos', 'middleware' => 'auth'], function() {

    Route::get('/show/{id}', [
        'uses'  =>  'PhotosController@show',
        'as'    =>  'photos.show'
    ]);
    Route::post('/create', [
        'uses'  =>  'PhotosController@store',
        'as'    =>  'photos.create'
    ]);
    Route::post('/update', [
        'uses'  =>  'PhotosController@update',
        'as'    =>  'photos.update'
    ]);
    Route::post('/delete/{id}', [
        'uses'  =>  'PhotosController@destroy',
        'as'    =>  'photos.delete'
    ]);
});

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests;
use App\User;
use Illuminate\Http\Request;

class HomeController extends Controller
{

    /**
     * Show users with number of photos.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $title = 'Users';
        $users = User::withCount('photos')->get();

        return view('home', compact('title', 'users'));
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')

    <div class="row">
        <div class="col-md-12">
            <div class="list-group">
                @foreach($users as $user)
                    <a href="{!! route('user.gallery', ['id' => $user->id]) !!}" class="list-group-item">
                        <span class="badge">{!! $user->photos_count !!}</span>
                        {!! $user->name !!}
                    </a>
                @endforeach
            </div>
        </div>
    </div>

@endsection